/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  important: '.msw-widget-root',
  darkMode: ['class', '.msw-widget-root.dark'], // Enable class-based dark mode scoped to widget
  safelist: [
    // Force generation of dark mode classes
    'dark:bg-gray-800',
    'dark:bg-gray-900',
    'dark:bg-gray-700',
    'dark:text-gray-100',
    'dark:text-gray-200',
    'dark:text-gray-300',
    'dark:text-gray-400',
    'dark:text-gray-500',
    'dark:border-gray-700',
    'dark:border-gray-600',
    'dark:hover:bg-gray-700',
    'dark:hover:bg-gray-800',
    'dark:hover:bg-gray-600',
    'dark:bg-blue-500',
    'dark:bg-blue-600',
    'dark:hover:bg-blue-600',
    'dark:bg-red-500',
    'dark:bg-red-600',
    'dark:hover:bg-red-600',
    'dark:text-red-400',
    'dark:text-red-300',
    'dark:bg-green-500',
    'dark:bg-green-600',
    'dark:hover:bg-green-600',
    'dark:text-green-300',
    'dark:bg-yellow-400',
    'dark:text-yellow-400',
    'dark:hover:bg-yellow-900/30',
    'dark:bg-yellow-900/20',
    'dark:bg-yellow-900/30',
    'dark:bg-blue-900/30',
    'dark:bg-green-900/30',
    'dark:bg-red-900/30',
    'dark:bg-purple-900/30',
    'dark:bg-indigo-900/30',
    'dark:text-blue-300',
    'dark:text-green-300',
    'dark:text-yellow-300',
    'dark:text-purple-300',
    'dark:text-indigo-300',
    'dark:text-red-300',
    'dark:placeholder-gray-400',
    'dark:focus:ring-blue-400',
    'dark:focus:ring-red-400',
    'dark:border-blue-400',
    'dark:border-red-400',
    'dark:border-yellow-800',
    'dark:hover:text-gray-200',
    'dark:hover:text-red-400',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

